// Code generated by templagen; DO NOT EDIT.
package main

import (
	_ "embed"
	"fmt"
	"io"
	"text/template"
)

//go:embed templates/メール.tmpl
var メールTplSource string

var templates = map[string]*template.Template{
	"メール": template.Must(template.New("メール").Option("missingkey=error").Parse(メールTplSource)),
}

// Templates returns a map of all templates
func Templates() map[string]*template.Template {
	return templates
}

// Render renders a template by name with the given data
func Render(w io.Writer, name string, data any) error {
	tmpl, ok := templates[name]
	if !ok {
		return fmt.Errorf("template %q not found", name)
	}
	return tmpl.Execute(w, data)
}

// ============================================================
// メール template
// ============================================================

// メール represents parameters for メール template
type メール struct {
	Name string
}

// Renderメール renders the メール template
func Renderメール(w io.Writer, p メール) error {
	tmpl, ok := templates["メール"]
	if !ok {
		return fmt.Errorf("template %q not found", "メール")
	}
	return tmpl.Execute(w, p)
}

