// Code generated by templagen; DO NOT EDIT.
package usertpl

import (
	_ "embed"
	"io"
	"text/template"
)

//go:embed user.tmpl
var tplSource string

func Template() *template.Template {
	return template.Must(template.New("tpl").Option("missingkey=error").Parse(tplSource))
}

type ItemsItem struct {
	ID int64
	Price float64
	Title string
}

type User struct {
	Age int
	Email *string
	Name string
}

type Params struct {
	Items []ItemsItem
	User User
}

func Render(w io.Writer, p Params) error { return Template().Execute(w, p) }

func RenderAny(w io.Writer, data any) error { return Template().Execute(w, data) }
