// Code generated by templagen; DO NOT EDIT.
package main

import (
	_ "embed"
	"fmt"
	"io"
	"text/template"
)

//go:embed templates/advanced.tmpl
var advancedTplSource string

//go:embed templates/basic_fields.tmpl
var basic_fieldsTplSource string

//go:embed templates/collections.tmpl
var collectionsTplSource string

//go:embed templates/control_flow.tmpl
var control_flowTplSource string

var templates = map[string]*template.Template{
	"advanced": template.Must(template.New("advanced").Option("missingkey=error").Parse(advancedTplSource)),
	"basic_fields": template.Must(template.New("basic_fields").Option("missingkey=error").Parse(basic_fieldsTplSource)),
	"collections": template.Must(template.New("collections").Option("missingkey=error").Parse(collectionsTplSource)),
	"control_flow": template.Must(template.New("control_flow").Option("missingkey=error").Parse(control_flowTplSource)),
}

// Templates returns a map of all templates
func Templates() map[string]*template.Template {
	return templates
}

type AdvancedCompany struct {
	Department AdvancedDepartment
}

type AdvancedDepartment struct {
	Team AdvancedTeam
}

type AdvancedManager struct {
	Name string
}

type AdvancedProject struct {
	Description string
	Name string
	Tasks []AdvancedTasksItem
}

type AdvancedTasksItem struct {
	Status string
	Title string
}

type AdvancedTeam struct {
	Manager AdvancedManager
}

// Advanced represents parameters for advanced template
type Advanced struct {
	Company AdvancedCompany
	Project AdvancedProject
}

type Basic_fieldsAuthor struct {
	Email string
	Name string
}

// Basic_fields represents parameters for basic_fields template
type Basic_fields struct {
	Author Basic_fieldsAuthor
	Title string
}

type CollectionsItemsItem struct {
	Description string
	ID string
	Title string
}

// Collections represents parameters for collections template
type Collections struct {
	Items []CollectionsItemsItem
	Meta map[string]string
}

type Control_flowSummary struct {
	Content string
	LastUpdated string
}

// Control_flow represents parameters for control_flow template
type Control_flow struct {
	DefaultMessage string
	Status string
	Summary Control_flowSummary
}

// RenderAdvanced renders the advanced template
func RenderAdvanced(w io.Writer, p Advanced) error {
	tmpl, ok := templates["advanced"]
	if !ok {
		return fmt.Errorf("template %q not found", "advanced")
	}
	return tmpl.Execute(w, p)
}

// RenderBasic_fields renders the basic_fields template
func RenderBasic_fields(w io.Writer, p Basic_fields) error {
	tmpl, ok := templates["basic_fields"]
	if !ok {
		return fmt.Errorf("template %q not found", "basic_fields")
	}
	return tmpl.Execute(w, p)
}

// RenderCollections renders the collections template
func RenderCollections(w io.Writer, p Collections) error {
	tmpl, ok := templates["collections"]
	if !ok {
		return fmt.Errorf("template %q not found", "collections")
	}
	return tmpl.Execute(w, p)
}

// RenderControl_flow renders the control_flow template
func RenderControl_flow(w io.Writer, p Control_flow) error {
	tmpl, ok := templates["control_flow"]
	if !ok {
		return fmt.Errorf("template %q not found", "control_flow")
	}
	return tmpl.Execute(w, p)
}

// Render renders a template by name with the given data
func Render(w io.Writer, name string, data any) error {
	tmpl, ok := templates[name]
	if !ok {
		return fmt.Errorf("template %q not found", name)
	}
	return tmpl.Execute(w, data)
}
