// Code generated by templagen; DO NOT EDIT.
package main

import (
	_ "embed"
	"fmt"
	"io"
	"text/template"
)

//go:embed templates/email.tmpl
var emailTplSource string

// Templates returns a map of all templates
func Templates() map[string]*template.Template {
	return map[string]*template.Template{
		"email": template.Must(template.New("email").Option("missingkey=error").Parse(emailTplSource)),
	}
}

type EmailUser struct {
	Name string
}

// Email represents parameters for email template
type Email struct {
	Message string
	User EmailUser
}

// RenderEmail renders the email template
func RenderEmail(w io.Writer, p Email) error {
	tmpl, ok := Templates()["email"]
	if !ok {
		return fmt.Errorf("template %q not found", "email")
	}
	return tmpl.Execute(w, p)
}

// Render renders a template by name with the given data
func Render(w io.Writer, name string, data any) error {
	tmpl, ok := Templates()[name]
	if !ok {
		return fmt.Errorf("template %q not found", name)
	}
	return tmpl.Execute(w, data)
}
