// Code generated by templagen; DO NOT EDIT.
package mailtpl

import (
	_ "embed"
	"io"
	"text/template"
)

//go:embed email.tmpl
var tplSource string

func Template() *template.Template {
	return template.Must(template.New("tpl").Option("missingkey=error").Parse(tplSource))
}

type User struct {
	Name string
}

type Params struct {
	Message string
	User User
}

func Render(w io.Writer, p Params) error { return Template().Execute(w, p) }

func RenderAny(w io.Writer, data any) error { return Template().Execute(w, data) }
