// Code generated by templagen; DO NOT EDIT.
package mailtpl

import (
	_ "embed"
	"io"
	"text/template"
)

//go:embed email.tmpl
var tplSource string

func Template() *template.Template {
	return template.Must(template.New("tpl").Option("missingkey=error").Parse(tplSource))
}

func RenderAny(w io.Writer, data any) error {
	return Template().Execute(w, data)
}
